/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MeRouteImport } from './routes/me'
import { Route as ConsultRouteImport } from './routes/consult'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiagnosisIndexRouteImport } from './routes/diagnosis.index'
import { Route as CarsIndexRouteImport } from './routes/cars.index'
import { Route as ResultTypeCodeRouteImport } from './routes/result.$typeCode'
import { Route as MydataResultRouteImport } from './routes/mydata.result'
import { Route as MydataIntroRouteImport } from './routes/mydata.intro'
import { Route as MydataConnectingRouteImport } from './routes/mydata.connecting'
import { Route as DiagnosisRevealRouteImport } from './routes/diagnosis.reveal'
import { Route as DiagnosisPrecisionRouteImport } from './routes/diagnosis.precision'
import { Route as DiagnosisOnboardingRouteImport } from './routes/diagnosis.onboarding'
import { Route as DiagnosisGateRouteImport } from './routes/diagnosis.gate'
import { Route as CarsIdRouteImport } from './routes/cars.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultRoute = ConsultRouteImport.update({
  id: '/consult',
  path: '/consult',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosisIndexRoute = DiagnosisIndexRouteImport.update({
  id: '/diagnosis/',
  path: '/diagnosis/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsIndexRoute = CarsIndexRouteImport.update({
  id: '/cars/',
  path: '/cars/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultTypeCodeRoute = ResultTypeCodeRouteImport.update({
  id: '/result/$typeCode',
  path: '/result/$typeCode',
  getParentRoute: () => rootRouteImport,
} as any)
const MydataResultRoute = MydataResultRouteImport.update({
  id: '/mydata/result',
  path: '/mydata/result',
  getParentRoute: () => rootRouteImport,
} as any)
const MydataIntroRoute = MydataIntroRouteImport.update({
  id: '/mydata/intro',
  path: '/mydata/intro',
  getParentRoute: () => rootRouteImport,
} as any)
const MydataConnectingRoute = MydataConnectingRouteImport.update({
  id: '/mydata/connecting',
  path: '/mydata/connecting',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosisRevealRoute = DiagnosisRevealRouteImport.update({
  id: '/diagnosis/reveal',
  path: '/diagnosis/reveal',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosisPrecisionRoute = DiagnosisPrecisionRouteImport.update({
  id: '/diagnosis/precision',
  path: '/diagnosis/precision',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosisOnboardingRoute = DiagnosisOnboardingRouteImport.update({
  id: '/diagnosis/onboarding',
  path: '/diagnosis/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosisGateRoute = DiagnosisGateRouteImport.update({
  id: '/diagnosis/gate',
  path: '/diagnosis/gate',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsIdRoute = CarsIdRouteImport.update({
  id: '/cars/$id',
  path: '/cars/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/compare': typeof CompareRoute
  '/consult': typeof ConsultRoute
  '/me': typeof MeRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/cars/$id': typeof CarsIdRoute
  '/diagnosis/gate': typeof DiagnosisGateRoute
  '/diagnosis/onboarding': typeof DiagnosisOnboardingRoute
  '/diagnosis/precision': typeof DiagnosisPrecisionRoute
  '/diagnosis/reveal': typeof DiagnosisRevealRoute
  '/mydata/connecting': typeof MydataConnectingRoute
  '/mydata/intro': typeof MydataIntroRoute
  '/mydata/result': typeof MydataResultRoute
  '/result/$typeCode': typeof ResultTypeCodeRoute
  '/cars/': typeof CarsIndexRoute
  '/diagnosis/': typeof DiagnosisIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/compare': typeof CompareRoute
  '/consult': typeof ConsultRoute
  '/me': typeof MeRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/cars/$id': typeof CarsIdRoute
  '/diagnosis/gate': typeof DiagnosisGateRoute
  '/diagnosis/onboarding': typeof DiagnosisOnboardingRoute
  '/diagnosis/precision': typeof DiagnosisPrecisionRoute
  '/diagnosis/reveal': typeof DiagnosisRevealRoute
  '/mydata/connecting': typeof MydataConnectingRoute
  '/mydata/intro': typeof MydataIntroRoute
  '/mydata/result': typeof MydataResultRoute
  '/result/$typeCode': typeof ResultTypeCodeRoute
  '/cars': typeof CarsIndexRoute
  '/diagnosis': typeof DiagnosisIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/compare': typeof CompareRoute
  '/consult': typeof ConsultRoute
  '/me': typeof MeRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/cars/$id': typeof CarsIdRoute
  '/diagnosis/gate': typeof DiagnosisGateRoute
  '/diagnosis/onboarding': typeof DiagnosisOnboardingRoute
  '/diagnosis/precision': typeof DiagnosisPrecisionRoute
  '/diagnosis/reveal': typeof DiagnosisRevealRoute
  '/mydata/connecting': typeof MydataConnectingRoute
  '/mydata/intro': typeof MydataIntroRoute
  '/mydata/result': typeof MydataResultRoute
  '/result/$typeCode': typeof ResultTypeCodeRoute
  '/cars/': typeof CarsIndexRoute
  '/diagnosis/': typeof DiagnosisIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/compare'
    | '/consult'
    | '/me'
    | '/privacy'
    | '/terms'
    | '/cars/$id'
    | '/diagnosis/gate'
    | '/diagnosis/onboarding'
    | '/diagnosis/precision'
    | '/diagnosis/reveal'
    | '/mydata/connecting'
    | '/mydata/intro'
    | '/mydata/result'
    | '/result/$typeCode'
    | '/cars/'
    | '/diagnosis/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/compare'
    | '/consult'
    | '/me'
    | '/privacy'
    | '/terms'
    | '/cars/$id'
    | '/diagnosis/gate'
    | '/diagnosis/onboarding'
    | '/diagnosis/precision'
    | '/diagnosis/reveal'
    | '/mydata/connecting'
    | '/mydata/intro'
    | '/mydata/result'
    | '/result/$typeCode'
    | '/cars'
    | '/diagnosis'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/compare'
    | '/consult'
    | '/me'
    | '/privacy'
    | '/terms'
    | '/cars/$id'
    | '/diagnosis/gate'
    | '/diagnosis/onboarding'
    | '/diagnosis/precision'
    | '/diagnosis/reveal'
    | '/mydata/connecting'
    | '/mydata/intro'
    | '/mydata/result'
    | '/result/$typeCode'
    | '/cars/'
    | '/diagnosis/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  CompareRoute: typeof CompareRoute
  ConsultRoute: typeof ConsultRoute
  MeRoute: typeof MeRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  CarsIdRoute: typeof CarsIdRoute
  DiagnosisGateRoute: typeof DiagnosisGateRoute
  DiagnosisOnboardingRoute: typeof DiagnosisOnboardingRoute
  DiagnosisPrecisionRoute: typeof DiagnosisPrecisionRoute
  DiagnosisRevealRoute: typeof DiagnosisRevealRoute
  MydataConnectingRoute: typeof MydataConnectingRoute
  MydataIntroRoute: typeof MydataIntroRoute
  MydataResultRoute: typeof MydataResultRoute
  ResultTypeCodeRoute: typeof ResultTypeCodeRoute
  CarsIndexRoute: typeof CarsIndexRoute
  DiagnosisIndexRoute: typeof DiagnosisIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consult': {
      id: '/consult'
      path: '/consult'
      fullPath: '/consult'
      preLoaderRoute: typeof ConsultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnosis/': {
      id: '/diagnosis/'
      path: '/diagnosis'
      fullPath: '/diagnosis/'
      preLoaderRoute: typeof DiagnosisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars/': {
      id: '/cars/'
      path: '/cars'
      fullPath: '/cars/'
      preLoaderRoute: typeof CarsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/$typeCode': {
      id: '/result/$typeCode'
      path: '/result/$typeCode'
      fullPath: '/result/$typeCode'
      preLoaderRoute: typeof ResultTypeCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mydata/result': {
      id: '/mydata/result'
      path: '/mydata/result'
      fullPath: '/mydata/result'
      preLoaderRoute: typeof MydataResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mydata/intro': {
      id: '/mydata/intro'
      path: '/mydata/intro'
      fullPath: '/mydata/intro'
      preLoaderRoute: typeof MydataIntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mydata/connecting': {
      id: '/mydata/connecting'
      path: '/mydata/connecting'
      fullPath: '/mydata/connecting'
      preLoaderRoute: typeof MydataConnectingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnosis/reveal': {
      id: '/diagnosis/reveal'
      path: '/diagnosis/reveal'
      fullPath: '/diagnosis/reveal'
      preLoaderRoute: typeof DiagnosisRevealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnosis/precision': {
      id: '/diagnosis/precision'
      path: '/diagnosis/precision'
      fullPath: '/diagnosis/precision'
      preLoaderRoute: typeof DiagnosisPrecisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnosis/onboarding': {
      id: '/diagnosis/onboarding'
      path: '/diagnosis/onboarding'
      fullPath: '/diagnosis/onboarding'
      preLoaderRoute: typeof DiagnosisOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnosis/gate': {
      id: '/diagnosis/gate'
      path: '/diagnosis/gate'
      fullPath: '/diagnosis/gate'
      preLoaderRoute: typeof DiagnosisGateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars/$id': {
      id: '/cars/$id'
      path: '/cars/$id'
      fullPath: '/cars/$id'
      preLoaderRoute: typeof CarsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  CompareRoute: CompareRoute,
  ConsultRoute: ConsultRoute,
  MeRoute: MeRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  CarsIdRoute: CarsIdRoute,
  DiagnosisGateRoute: DiagnosisGateRoute,
  DiagnosisOnboardingRoute: DiagnosisOnboardingRoute,
  DiagnosisPrecisionRoute: DiagnosisPrecisionRoute,
  DiagnosisRevealRoute: DiagnosisRevealRoute,
  MydataConnectingRoute: MydataConnectingRoute,
  MydataIntroRoute: MydataIntroRoute,
  MydataResultRoute: MydataResultRoute,
  ResultTypeCodeRoute: ResultTypeCodeRoute,
  CarsIndexRoute: CarsIndexRoute,
  DiagnosisIndexRoute: DiagnosisIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
