/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiagnosisIndexRouteImport } from './routes/diagnosis.index'
import { Route as ResultTypeCodeRouteImport } from './routes/result.$typeCode'
import { Route as DiagnosisOnboardingRouteImport } from './routes/diagnosis.onboarding'
import { Route as DiagnosisGateRouteImport } from './routes/diagnosis.gate'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosisIndexRoute = DiagnosisIndexRouteImport.update({
  id: '/diagnosis/',
  path: '/diagnosis/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultTypeCodeRoute = ResultTypeCodeRouteImport.update({
  id: '/result/$typeCode',
  path: '/result/$typeCode',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosisOnboardingRoute = DiagnosisOnboardingRouteImport.update({
  id: '/diagnosis/onboarding',
  path: '/diagnosis/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosisGateRoute = DiagnosisGateRouteImport.update({
  id: '/diagnosis/gate',
  path: '/diagnosis/gate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/terms': typeof TermsRoute
  '/diagnosis/gate': typeof DiagnosisGateRoute
  '/diagnosis/onboarding': typeof DiagnosisOnboardingRoute
  '/result/$typeCode': typeof ResultTypeCodeRoute
  '/diagnosis/': typeof DiagnosisIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/terms': typeof TermsRoute
  '/diagnosis/gate': typeof DiagnosisGateRoute
  '/diagnosis/onboarding': typeof DiagnosisOnboardingRoute
  '/result/$typeCode': typeof ResultTypeCodeRoute
  '/diagnosis': typeof DiagnosisIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/terms': typeof TermsRoute
  '/diagnosis/gate': typeof DiagnosisGateRoute
  '/diagnosis/onboarding': typeof DiagnosisOnboardingRoute
  '/result/$typeCode': typeof ResultTypeCodeRoute
  '/diagnosis/': typeof DiagnosisIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/terms'
    | '/diagnosis/gate'
    | '/diagnosis/onboarding'
    | '/result/$typeCode'
    | '/diagnosis/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/terms'
    | '/diagnosis/gate'
    | '/diagnosis/onboarding'
    | '/result/$typeCode'
    | '/diagnosis'
  id:
    | '__root__'
    | '/'
    | '/terms'
    | '/diagnosis/gate'
    | '/diagnosis/onboarding'
    | '/result/$typeCode'
    | '/diagnosis/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TermsRoute: typeof TermsRoute
  DiagnosisGateRoute: typeof DiagnosisGateRoute
  DiagnosisOnboardingRoute: typeof DiagnosisOnboardingRoute
  ResultTypeCodeRoute: typeof ResultTypeCodeRoute
  DiagnosisIndexRoute: typeof DiagnosisIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnosis/': {
      id: '/diagnosis/'
      path: '/diagnosis'
      fullPath: '/diagnosis/'
      preLoaderRoute: typeof DiagnosisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/$typeCode': {
      id: '/result/$typeCode'
      path: '/result/$typeCode'
      fullPath: '/result/$typeCode'
      preLoaderRoute: typeof ResultTypeCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnosis/onboarding': {
      id: '/diagnosis/onboarding'
      path: '/diagnosis/onboarding'
      fullPath: '/diagnosis/onboarding'
      preLoaderRoute: typeof DiagnosisOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnosis/gate': {
      id: '/diagnosis/gate'
      path: '/diagnosis/gate'
      fullPath: '/diagnosis/gate'
      preLoaderRoute: typeof DiagnosisGateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TermsRoute: TermsRoute,
  DiagnosisGateRoute: DiagnosisGateRoute,
  DiagnosisOnboardingRoute: DiagnosisOnboardingRoute,
  ResultTypeCodeRoute: ResultTypeCodeRoute,
  DiagnosisIndexRoute: DiagnosisIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
