/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiagnosisIndexRouteImport } from './routes/diagnosis.index'
import { Route as CarsIndexRouteImport } from './routes/cars.index'
import { Route as ResultTypeCodeRouteImport } from './routes/result.$typeCode'
import { Route as MydataResultRouteImport } from './routes/mydata.result'
import { Route as MydataIntroRouteImport } from './routes/mydata.intro'
import { Route as MydataConnectingRouteImport } from './routes/mydata.connecting'
import { Route as DiagnosisOnboardingRouteImport } from './routes/diagnosis.onboarding'
import { Route as DiagnosisGateRouteImport } from './routes/diagnosis.gate'
import { Route as CarsIdRouteImport } from './routes/cars.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosisIndexRoute = DiagnosisIndexRouteImport.update({
  id: '/diagnosis/',
  path: '/diagnosis/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsIndexRoute = CarsIndexRouteImport.update({
  id: '/cars/',
  path: '/cars/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultTypeCodeRoute = ResultTypeCodeRouteImport.update({
  id: '/result/$typeCode',
  path: '/result/$typeCode',
  getParentRoute: () => rootRouteImport,
} as any)
const MydataResultRoute = MydataResultRouteImport.update({
  id: '/mydata/result',
  path: '/mydata/result',
  getParentRoute: () => rootRouteImport,
} as any)
const MydataIntroRoute = MydataIntroRouteImport.update({
  id: '/mydata/intro',
  path: '/mydata/intro',
  getParentRoute: () => rootRouteImport,
} as any)
const MydataConnectingRoute = MydataConnectingRouteImport.update({
  id: '/mydata/connecting',
  path: '/mydata/connecting',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosisOnboardingRoute = DiagnosisOnboardingRouteImport.update({
  id: '/diagnosis/onboarding',
  path: '/diagnosis/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosisGateRoute = DiagnosisGateRouteImport.update({
  id: '/diagnosis/gate',
  path: '/diagnosis/gate',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsIdRoute = CarsIdRouteImport.update({
  id: '/cars/$id',
  path: '/cars/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/cars/$id': typeof CarsIdRoute
  '/diagnosis/gate': typeof DiagnosisGateRoute
  '/diagnosis/onboarding': typeof DiagnosisOnboardingRoute
  '/mydata/connecting': typeof MydataConnectingRoute
  '/mydata/intro': typeof MydataIntroRoute
  '/mydata/result': typeof MydataResultRoute
  '/result/$typeCode': typeof ResultTypeCodeRoute
  '/cars/': typeof CarsIndexRoute
  '/diagnosis/': typeof DiagnosisIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/cars/$id': typeof CarsIdRoute
  '/diagnosis/gate': typeof DiagnosisGateRoute
  '/diagnosis/onboarding': typeof DiagnosisOnboardingRoute
  '/mydata/connecting': typeof MydataConnectingRoute
  '/mydata/intro': typeof MydataIntroRoute
  '/mydata/result': typeof MydataResultRoute
  '/result/$typeCode': typeof ResultTypeCodeRoute
  '/cars': typeof CarsIndexRoute
  '/diagnosis': typeof DiagnosisIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/cars/$id': typeof CarsIdRoute
  '/diagnosis/gate': typeof DiagnosisGateRoute
  '/diagnosis/onboarding': typeof DiagnosisOnboardingRoute
  '/mydata/connecting': typeof MydataConnectingRoute
  '/mydata/intro': typeof MydataIntroRoute
  '/mydata/result': typeof MydataResultRoute
  '/result/$typeCode': typeof ResultTypeCodeRoute
  '/cars/': typeof CarsIndexRoute
  '/diagnosis/': typeof DiagnosisIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compare'
    | '/privacy'
    | '/terms'
    | '/cars/$id'
    | '/diagnosis/gate'
    | '/diagnosis/onboarding'
    | '/mydata/connecting'
    | '/mydata/intro'
    | '/mydata/result'
    | '/result/$typeCode'
    | '/cars/'
    | '/diagnosis/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare'
    | '/privacy'
    | '/terms'
    | '/cars/$id'
    | '/diagnosis/gate'
    | '/diagnosis/onboarding'
    | '/mydata/connecting'
    | '/mydata/intro'
    | '/mydata/result'
    | '/result/$typeCode'
    | '/cars'
    | '/diagnosis'
  id:
    | '__root__'
    | '/'
    | '/compare'
    | '/privacy'
    | '/terms'
    | '/cars/$id'
    | '/diagnosis/gate'
    | '/diagnosis/onboarding'
    | '/mydata/connecting'
    | '/mydata/intro'
    | '/mydata/result'
    | '/result/$typeCode'
    | '/cars/'
    | '/diagnosis/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareRoute: typeof CompareRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  CarsIdRoute: typeof CarsIdRoute
  DiagnosisGateRoute: typeof DiagnosisGateRoute
  DiagnosisOnboardingRoute: typeof DiagnosisOnboardingRoute
  MydataConnectingRoute: typeof MydataConnectingRoute
  MydataIntroRoute: typeof MydataIntroRoute
  MydataResultRoute: typeof MydataResultRoute
  ResultTypeCodeRoute: typeof ResultTypeCodeRoute
  CarsIndexRoute: typeof CarsIndexRoute
  DiagnosisIndexRoute: typeof DiagnosisIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnosis/': {
      id: '/diagnosis/'
      path: '/diagnosis'
      fullPath: '/diagnosis/'
      preLoaderRoute: typeof DiagnosisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars/': {
      id: '/cars/'
      path: '/cars'
      fullPath: '/cars/'
      preLoaderRoute: typeof CarsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/$typeCode': {
      id: '/result/$typeCode'
      path: '/result/$typeCode'
      fullPath: '/result/$typeCode'
      preLoaderRoute: typeof ResultTypeCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mydata/result': {
      id: '/mydata/result'
      path: '/mydata/result'
      fullPath: '/mydata/result'
      preLoaderRoute: typeof MydataResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mydata/intro': {
      id: '/mydata/intro'
      path: '/mydata/intro'
      fullPath: '/mydata/intro'
      preLoaderRoute: typeof MydataIntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mydata/connecting': {
      id: '/mydata/connecting'
      path: '/mydata/connecting'
      fullPath: '/mydata/connecting'
      preLoaderRoute: typeof MydataConnectingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnosis/onboarding': {
      id: '/diagnosis/onboarding'
      path: '/diagnosis/onboarding'
      fullPath: '/diagnosis/onboarding'
      preLoaderRoute: typeof DiagnosisOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnosis/gate': {
      id: '/diagnosis/gate'
      path: '/diagnosis/gate'
      fullPath: '/diagnosis/gate'
      preLoaderRoute: typeof DiagnosisGateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars/$id': {
      id: '/cars/$id'
      path: '/cars/$id'
      fullPath: '/cars/$id'
      preLoaderRoute: typeof CarsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareRoute: CompareRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  CarsIdRoute: CarsIdRoute,
  DiagnosisGateRoute: DiagnosisGateRoute,
  DiagnosisOnboardingRoute: DiagnosisOnboardingRoute,
  MydataConnectingRoute: MydataConnectingRoute,
  MydataIntroRoute: MydataIntroRoute,
  MydataResultRoute: MydataResultRoute,
  ResultTypeCodeRoute: ResultTypeCodeRoute,
  CarsIndexRoute: CarsIndexRoute,
  DiagnosisIndexRoute: DiagnosisIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
